/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


//#define MCU_Act_As_Slave
#define MCU_Act_As_Master


#include <stm32f103x6.h>
#include "Stm32_F103C6_GPIO.h"
#include "Stm32_F103C6_USART.h"
#include "Stm32_F103C6_SPI.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


unsigned char ch ;


void UART_Call_Back(){
#ifdef MCU_Act_As_Master
	MCAL_UART_Receive(USART1, &ch, USART_disable);
	MCAL_UART_Transmit(USART1, &ch, USART_enable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET);
	MCAL_SPI_Transmit_Receive(SPI1,&ch, SPI_enable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
#endif
}

void clock_init()
{
	//Enable port A clock
	RCC_GPIOA_CLK_EN();
	//Enable port B clock
	RCC_GPIOB_CLK_EN();
	//Enable AFIO clock
	RCC_AFIO_CLK_EN();
}
void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}


int main(void)
{
	clock_init();

	USART_Config_t USART1_Config;

	USART1_Config.BaudRate = UART_BaudRate_115200;
	USART1_Config.HwFlowCtl = UART_HwFlowCtl_NONE;
	USART1_Config.IRQ_Enable = UART_IRQ_Enable_RXNEIE;
	USART1_Config.P_IRQ_CallBack = UART_Call_Back;
	USART1_Config.Parity = UART_Parity_NONE;
	USART1_Config.Payload_Length = UART_Payload_Length_8B;
	USART1_Config.StopBits = UART_StopBits_1;
	USART1_Config.USART_Mode = UART_Mode_TX_RX;
	MCAL_UART_Init(USART1, &USART1_Config);
	MCAL_UART_GPIO_Set_Pins(USART1);

	SPI_CONFIG_t spiCFG;
	spiCFG.CLK_Phase = SPI_CLK_Phase_First_Edge;
	spiCFG.CLK_Polarity = SPI_CLK_Polarity_When1;
	spiCFG.Data_Size = SPI_Data_Size_8BIT;
	spiCFG.Communicatin_Mode = SPI_Communicatin_Mode_2Lines;
	spiCFG.Frame_Format = SPI_Frame_Format_MSB;
	spiCFG.Baud_Rate= SPI_BaudRate_8;

#ifdef MCU_Act_As_Master
	spiCFG.SPI_Mode = SPI_Mode_Master;
	spiCFG.IRQ_Enable = SPI_IRQ_NONE;
	spiCFG.Slave_S_management = SPI_Slave_S_management_SW_Internal_SET;
	spiCFG.IRQ_HANDLER = NULL;

	/* Configuration of SS */
	GPIO_PIN_CONFIG_T SS_Config;

	/* Configure SS at PA4 by GPIO */
	SS_Config.GPIO_PIN_NUMBER = GPIO_PIN_4;
	SS_Config.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	SS_Config.GPIO_OUTPUT_SPEED = GPIO_SPEED_10MHz;

	MCAL_GPIO_Init(GPIOA, &SS_Config);
#endif

	MCAL_SPI_Init(SPI1, &spiCFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);

	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
	while(1){

	}
}
