/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Ahmed Adel Wafdy
typedef volatile unsigned int vuint32_t;
#include <stdint.h>

#define RCC_BASE		0x40021000
#define GPIOA_BASE		0x40010800
#define RCC_APB2ENR		*(volatile uint32_t *)(RCC_BASE + 0x18)
#define GPIOA_CRH		*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define RCC_IOPAEN		(1<<2)
#define GPIOA13			(1UL<<13)

typedef union {
	vuint32_t	all_fields;
	struct{
		vuint32_t	reserved:13;
		vuint32_t	pin13:1;
	}pin;
}R_ODR_t;
volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE +0x0C);

int main(void)
{
	/* code */
	RCC_APB2ENR |= RCC_IOPAEN;
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		R_ODR->pin.pin13 = 1;
		for(int i = 0; i < 5000; i++);
		R_ODR->pin.pin13 = 0;
		for(int i = 0; i < 5000; i++);
	}

}
