/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Ahmed Adel Wafdy
typedef volatile unsigned int vuint32_t;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>


//GPIOA Config ====> input pin0 - input pin13
#define GPIOA_BASE		0x40010800
#define GPIOA_CRL		*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH		*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR		*(volatile uint32_t *)(GPIOA_BASE + 0x08)
//===========================
//GPIOB Config ====> input pin0 - input pin13
#define GPIOB_BASE		0x40010C00
#define GPIOB_CRL		*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOB_CRH		*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOB_ODR		*(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOB_IDR		*(volatile uint32_t *)(GPIOA_BASE + 0x08)
//===========================

//Reset and clock control
#define RCC_BASE		0x40021000
#define RCC_IOPAEN		(1<<2)
#define RCC_APB2ENR		*(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR		*(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR			*(volatile uint32_t *)(RCC_BASE + 0x00)


void clock_init()
{
	//Enable port A clock
	RCC_APB2ENR |= RCC_IOPAEN;
	//Enable port B clock
	RCC_APB2ENR |= (1<<3);
}
//PORTB pins 1,13 output---PORTA pin1,13 input
void GPIO_init(){
	//put reset value
	GPIOA_CRL = 0;
	GPIOA_CRH = 0;
	GPIOA_IDR =0;
	GPIOB_CRL = 0;
	GPIOB_CRH = 0;
	GPIOB_ODR =0;
	//PORTA pins 1,13 ===> input mode ,floating input
	// PORTA pin 1 ===>00: input mode ===>01: Floating input (reset state)
	GPIOA_CRL |= (0b01<<6);
	// PORTA pin 13 ===>00: input mode ===>01: Floating input (reset state)
	GPIOA_CRH &= ~(0b11<<20);
	GPIOA_CRH |= (0b01<<22);
	//==========================
	//PORTB pins 1,13
	//PORTB pin1 ===>01: Output mode, max speed 10 MHz.===>00: General purpose output push-pull
	GPIOB_CRL |= (0b01<<4);
	GPIOB_CRL &= ~(0b11<<6);
	//PORTB pin13 ===>01: Output mode, max speed 10 MHz.===>00: General purpose output push-pull
	GPIOB_CRH |= (0b01<<20);
	GPIOB_CRH &= ~(0b11<<22);
}
void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();
	while(1){
		if((GPIOA_IDR & (1<<1) >>1) ==0 ){
			GPIOB_ODR ^= 1<<1;
			//while((GPIOA_IDR & (1<<1) >>1) ==0);//single pressing
		}
		if((GPIOA_IDR & (1<<13) >>13) ==1){
			GPIOB_ODR ^= 1<<13;
		}
		wait_ms(1);
	}
}

