/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f103x6.h>
#include "Stm32_F103C6_GPIO.h"
#include "Stm32_F103C6_EXTI.h"
#include "lcd.h"
#include "keypad.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint32_t IRQ_flag = 0;

void clock_init()
{
	//Enable port A clock
	RCC_GPIOA_CLK_EN();
	//Enable port B clock
	RCC_GPIOB_CLK_EN();
	//Enable AFIO clock
	RCC_AFIO_CLK_EN();
}
void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}

void IRQ_EXTI9_callback(void){
	IRQ_flag = 1;
	lcd_send_string("IRQ EXTI9 is happened...!");

}
int main(void)
{
	clock_init();
	lcd_init();
	lcd_clear();
	EXTI_PIN_CONFIG_t EXTI_cfg;
	EXTI_cfg.EXTI_PIN = EXTI9PB9;
	EXTI_cfg.TRIGGER_CASE = EXTI_TRIGGER_RISING_EDGE;
	EXTI_cfg.IRQ_HANDLER = IRQ_EXTI9_callback;
	EXTI_cfg.IRQ_EN = EXTI_IRQ_ENABLE;
	MCAL_EXTI_Init(&EXTI_cfg);
	IRQ_flag = 1;
	lcd_clear();
	while(1){
		if(IRQ_flag){
			lcd_clear();
			IRQ_flag = 0;
		}
	}
}
